### ISSUE TITLE
Breaking changes from v3 to v4 ?

### ISSUE THREAD

**Issue by vpratfr** [yarkovaleksei/vue2-storage#30]
I have looked for documentation about the releases but I failed to find what the changes are in version 4.x

We are currently using the latest 3.x version and before making the update I was wondering what breaking changes I should be aware of.

Would be great to have a CHANGELOG.md file to list major changes from a version to another.

**Comment by yarkovaleksei** [comment]
Yes, I agree, the CHANGELOG.md file is needed, but for some reason I missed it.

 About the changes.  Internal implementation has not changed.  The plugin was correctly rewritten in TypeScript, for support by editors.  And the connection error was fixed using unpkg.com.

 Otherwise, everything is as before.
